services:
    ncmf.security.role_hierarchy:
        class: NCMF\RoleHierarchy\Role\RoleHierarchy
        arguments: ['%security.role_hierarchy.roles%']
    ncmf.security.role_hierarchy_voter:
        class: NCMF\RoleHierarchy\Role\RoleHierarchyVoter
        arguments: ['@ncmf.security.role_hierarchy']
        tags:
            - { name: security.voter, priority: 245 }
