services:
    ncmf.security.role_hierarchy:
        class: NCMF\RoleHierarchyBundle\Role\RoleHierarchy
        arguments: ['%security.role_hierarchy.roles%', '@doctrine.orm.entity_manager']
    ncmf.security.role_hierarchy_voter:
        class: NCMF\RoleHierarchyBundle\Role\RoleHierarchyVoter
        arguments: ['@ncmf.security.role_hierarchy']
        tags:
            - { name: security.voter, priority: 245 }
